version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=igor
    #  - MONGO_INITDB_ROOT_PASSWORD=pass
  backend:
    build: ./
    ports:
      - '80:80'
    depends_on:
      - mongodb
    
  frontend:
    build: ../frontend
    ports:
      - '3000:3000'
    volumes:
      - ../frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
