version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=igor
    #  - MONGO_INITDB_ROOT_PASSWORD=pass
  backend:
    build: ./
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    
  # frontend:

volumes:
  data:
